name: flutter_ml_kit
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  app_settings: ^5.0.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  permission_handler: ^10.4.3
  photo_manager: ^2.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true